### ISSUE TITLE
webextension dashboard improvements

### ISSUE THREAD

**Issue by mixedpuppy** [mozilla/addons-pm#582]
Whiteboard bugs:

* Can we consolidate all stockwell bugs into one.
* prod_bugs doesn't seem useful
* mv3 bugs are all prefixed with "mv3:", and have mv3:m1|m2|m3|future.  These could replace the other collapsed whiteboard bugs, or could go into a row of their own

"Compat bugs Webextensions" can be removed
P3 and Total Opened could be removed

Whiteboard could go to top, and need infos to bottom.

**Comment by muffinresearch** [comment]
> Whiteboard bugs:
> 
>     * Can we consolidate all stockwell bugs into one.

If I understand this correctly - you want a count of all bugs "stockwell*" would that be right? Or, do you want a specific set of stockwell related tags to be combined and ignore the others?

> 
>     * prod_bugs doesn't seem useful

Krupa wanted this for the QA team. 

> 
>     * mv3 bugs are all prefixed with "mv3:", and have mv3:m1|m2|m3|future.  These could replace the other collapsed whiteboard bugs, or could go into a row of their own
> 
> 
> "Compat bugs Webextensions" can be removed
> P3 and Total Opened could be removed
> 
> Whiteboard could go to top, and need infos to bottom.

Otherwise this sounds fine, I'll file individual bugs to make this easier to track.
